const mockParts = {
  // ---------- CPU ----------
  cpu: [
    {
      id: "cpu-athlon-3000g",
      type: "cpu",
      name: "AMD Athlon 3000G",
      brand: "AMD",
      socket: "AM4",
      coreCount: 2,
      clockSpeed: "3.5 GHz",
      boostClock: "N/A",
      architecture: "Zen",
      tdp: "35 W",
      graphics: "Vega",
      tier: "budget",
      price: "$49",
      rating: 4.0,
      image: "/images/cpu/athlon3000g.jpeg"
    },
    {
      id: "cpu-ryzen-3-3200g",
      type: "cpu",
      name: "AMD Ryzen 3 3200G",
      brand: "AMD",
      socket: "AM4",
      coreCount: 4,
      clockSpeed: "3.6 GHz",
      boostClock: "4.0 GHz",
      architecture: "Zen+",
      tdp: "65 W",
      graphics: "Vega 8",
      tier: "budget",
      price: "$89",
      rating: 4.4,
      image: "/images/cpu/ryzen-3-3200g.jpg"
    },
    {
      id: "cpu-i3-10100",
      type: "cpu",
      name: "Intel Core i3-10100",
      brand: "Intel",
      socket: "LGA1200",
      coreCount: 4,
      clockSpeed: "3.6 GHz",
      boostClock: "4.3 GHz",
      architecture: "Comet Lake",
      tdp: "65 W",
      graphics: "UHD 630",
      tier: "budget",
      price: "$99",
      rating: 4.6,
      image: "/images/cpu/i3-10100.jpg"
    },
    {
      id: "cpu-ryzen-5-5600g",
      type: "cpu",
      name: "AMD Ryzen 5 5600G",
      brand: "AMD",
      socket: "AM4",
      coreCount: 6,
      clockSpeed: "3.9 GHz",
      boostClock: "4.4 GHz",
      architecture: "Zen 3",
      tdp: "65 W",
      graphics: "Radeon",
      tier: "midrange",
      price: "$169",
      rating: 4.8,
      image: "/images/cpu/ryzen-5-5600g.jpg"
    },
    {
      id: "cpu-i3-12100",
      type: "cpu",
      name: "Intel Core i3-12100",
      brand: "Intel",
      socket: "LGA1700",
      coreCount: 4,
      clockSpeed: "3.3 GHz",
      boostClock: "4.3 GHz",
      architecture: "Alder Lake",
      tdp: "60 W",
      graphics: "UHD 730",
      tier: "midrange",
      price: "$129",
      rating: 4.9,
      image: "/images/cpu/i3-12100.jpg"
    },
    {
      id: "cpu-i5-12400",
      type: "cpu",
      name: "Intel Core i5-12400",
      brand: "Intel",
      socket: "LGA1700",
      coreCount: 6,
      clockSpeed: "2.5 GHz",
      boostClock: "4.4 GHz",
      architecture: "Alder Lake",
      tdp: "65 W",
      graphics: "UHD 730",
      tier: "midrange",
      price: "$179",
      rating: 4.9,
      image: "/images/cpu/i5-12400.jpg"
    },
    {
      id: "cpu-ryzen-5-5600",
      type: "cpu",
      name: "AMD Ryzen 5 5600",
      brand: "AMD",
      socket: "AM4",
      coreCount: 6,
      clockSpeed: "3.5 GHz",
      boostClock: "4.4 GHz",
      architecture: "Zen 3",
      tdp: "65 W",
      graphics: "None",
      tier: "midrange",
      price: "$179",
      rating: 4.8,
      image: "/images/cpu/ryzen-5-5600.jpg"
    },
    {
      id: "cpu-ryzen-7-7700x",
      type: "cpu",
      name: "AMD Ryzen 7 7700X",
      brand: "AMD",
      socket: "AM5",
      coreCount: 8,
      clockSpeed: "4.5 GHz",
      boostClock: "5.4 GHz",
      architecture: "Zen 4",
      tdp: "120 W",
      graphics: "RDNA 2",
      tier: "high-end",
      price: "$399",
      rating: 4.9,
      image: "/images/cpu/ryzen-7-7700x.jpg"
    },
    {
      id: "cpu-i7-13700k",
      type: "cpu",
      name: "Intel Core i7-13700K",
      brand: "Intel",
      socket: "LGA1700",
      coreCount: 16,
      clockSpeed: "3.4 GHz",
      boostClock: "5.4 GHz",
      architecture: "Raptor Lake",
      tdp: "125 W",
      graphics: "UHD 770",
      tier: "high-end",
      price: "$429",
      rating: 4.9,
      image: "/images/cpu/i7-13700k.jpg"
    },
    {
      id: "cpu-i9-13900k",
      type: "cpu",
      name: "Intel Core i9-13900K",
      brand: "Intel",
      socket: "LGA1700",
      coreCount: 24,
      clockSpeed: "3.0 GHz",
      boostClock: "5.8 GHz",
      architecture: "Raptor Lake",
      tdp: "125 W",
      graphics: "UHD 770",
      tier: "enthusiast",
      price: "$699",
      rating: 5.0,
      image: "/images/cpu/i9-13900k.jpg"
    }
  ],

  // ---------- CPU Coolers ----------
  "cpu-cooler": [
    {
      id: "cool-wraith-stealth",
      type: "cpu-cooler",
      name: "AMD Wraith Stealth",
      brand: "AMD",
      coolerType: "Air",
      tdpSupport: "65 W",
      price: "$10",
      rating: 4.0,
      image: "/images/cpu-cooler/wraith-stealth.jpg"
    },
    {
      id: "cool-intel-stock",
      type: "cpu-cooler",
      name: "Intel Stock Cooler",
      brand: "Intel",
      coolerType: "Air",
      tdpSupport: "65 W",
      price: "$50",
      rating: 4.0,
      image: "/images/cpu-cooler/intel-stock.jpg"
    },
    {
      id: "cool-arctic-alpine-12",
      type: "cpu-cooler",
      name: "Arctic Alpine 12",
      brand: "Arctic",
      coolerType: "Air",
      tdpSupport: "95 W",
      price: "$19",
      rating: 4.2,
      image: "/images/cpu-cooler/arctic-alpine-12.jpg"
    },
    {
      id: "cool-gammaxx-200",
      type: "cpu-cooler",
      name: "DeepCool Gammaxx 200",
      brand: "DeepCool",
      coolerType: "Air",
      tdpSupport: "120 W",
      price: "$24",
      rating: 4.3,
      image: "/images/cpu-cooler/gammaxx-200.jpg"
    },
    {
      id: "cool-hyper-212",
      type: "cpu-cooler",
      name: "Cooler Master Hyper 212",
      brand: "Cooler Master",
      coolerType: "Air",
      tdpSupport: "160 W",
      price: "$39",
      rating: 4.8,
      image: "/images/cpu-cooler/hyper-212.jpg"
    },
    {
      id: "cool-gammaxx-400",
      type: "cpu-cooler",
      name: "DeepCool Gammaxx 400",
      brand: "DeepCool",
      coolerType: "Air",
      tdpSupport: "150 W",
      price: "$29",
      rating: 4.6,
      image: "/images/cpu-cooler/gammaxx-400.jpg"
    },
    {
      id: "cool-nh-u12s",
      type: "cpu-cooler",
      name: "Noctua NH-U12S",
      brand: "Noctua",
      coolerType: "Air",
      tdpSupport: "180 W",
      price: "$79",
      rating: 4.9,
      image: "/images/cpu-cooler/nh-u12s.jpg"
    },
    {
      id: "cool-nh-d15",
      type: "cpu-cooler",
      name: "Noctua NH-D15",
      brand: "Noctua",
      coolerType: "Air",
      tdpSupport: "220 W",
      price: "$109",
      rating: 4.9,
      image: "/images/cpu-cooler/nh-d15.jpg"
    },
    {
      id: "cool-h100i",
      type: "cpu-cooler",
      name: "Corsair H100i RGB",
      brand: "Corsair",
      coolerType: "AIO 240mm",
      tdpSupport: "220 W",
      price: "$139",
      rating: 4.8,
      image: "/images/cpu-cooler/h100i.jpg"
    },
    {
      id: "cool-kraken-x63",
      type: "cpu-cooler",
      name: "NZXT Kraken X63",
      brand: "NZXT",
      coolerType: "AIO 280mm",
      tdpSupport: "250 W",
      price: "$159",
      rating: 4.8,
      image: "/images/cpu-cooler/kraken-x63.jpg"
    }
  ],

  // ---------- Motherboard ----------
  motherboard: [
    {
      id: "mb-a320m-hdv",
      type: "motherboard",
      name: "ASRock A320M-HDV",
      brand: "ASRock",
      socket: "AM4",
      chipset: "A320",
      formFactor: "mATX",
      memoryType: "DDR4",
      maxMemory: "32 GB",
      price: "$59",
      rating: 4.2,
      image: "/images/motherboard/a320m-hdv.jpg"
    },
    {
      id: "mb-a520m-s2h",
      type: "motherboard",
      name: "Gigabyte A520M S2H",
      brand: "Gigabyte",
      socket: "AM4",
      chipset: "A520",
      formFactor: "mATX",
      memoryType: "DDR4",
      maxMemory: "64 GB",
      price: "$69",
      rating: 4.4,
      image: "/images/motherboard/a520m-s2h.jpg"
    },
    {
      id: "mb-b450m-ds3h",
      type: "motherboard",
      name: "Gigabyte B450M DS3H",
      brand: "Gigabyte",
      socket: "AM4",
      chipset: "B450",
      formFactor: "mATX",
      memoryType: "DDR4",
      maxMemory: "64 GB",
      price: "$79",
      rating: 4.6,
      image: "/images/motherboard/b450m-ds3h.jpg"
    },
    {
      id: "mb-b550-tomahawk",
      type: "motherboard",
      name: "MSI B550 Tomahawk",
      brand: "MSI",
      socket: "AM4",
      chipset: "B550",
      formFactor: "ATX",
      memoryType: "DDR4",
      maxMemory: "128 GB",
      price: "$179",
      rating: 4.9,
      image: "/images/motherboard/b550-tomahawk.jpg"
    },
    {
      id: "mb-x570-elite",
      type: "motherboard",
      name: "Gigabyte X570 Aorus Elite",
      brand: "Gigabyte",
      socket: "AM4",
      chipset: "X570",
      formFactor: "ATX",
      memoryType: "DDR4",
      maxMemory: "128 GB",
      price: "$249",
      rating: 4.8,
      image: "/images/motherboard/x570-elite.jpg"
    },
    {
      id: "mb-h510m-s2h",
      type: "motherboard",
      name: "Gigabyte H510M S2H",
      brand: "Gigabyte",
      socket: "LGA1200",
      chipset: "H510",
      formFactor: "mATX",
      memoryType: "DDR4",
      maxMemory: "64 GB",
      price: "$69",
      rating: 4.5,
      image: "/images/motherboard/h510m-s2h.jpg"
    },
    {
      id: "mb-h610m",
      type: "motherboard",
      name: "ASRock H610M",
      brand: "ASRock",
      socket: "LGA1700",
      chipset: "H610",
      formFactor: "mATX",
      memoryType: "DDR4",
      maxMemory: "64 GB",
      price: "$79",
      rating: 4.6,
      image: "/images/motherboard/h610m.jpg"
    },
    {
      id: "mb-b660m-ds3h",
      type: "motherboard",
      name: "Gigabyte B660M DS3H",
      brand: "Gigabyte",
      socket: "LGA1700",
      chipset: "B660",
      formFactor: "mATX",
      memoryType: "DDR4",
      maxMemory: "128 GB",
      price: "$109",
      rating: 4.7,
      image: "/images/motherboard/b660m-ds3h.jpg"
    },
    {
      id: "mb-z690-prime",
      type: "motherboard",
      name: "ASUS Prime Z690-P",
      brand: "ASUS",
      socket: "LGA1700",
      chipset: "Z690",
      formFactor: "ATX",
      memoryType: "DDR5",
      maxMemory: "128 GB",
      price: "$249",
      rating: 4.8,
      image: "/images/motherboard/z690-prime.jpg"
    },
    {
      id: "mb-z790-rog",
      type: "motherboard",
      name: "ASUS ROG Z790-E",
      brand: "ASUS",
      socket: "LGA1700",
      chipset: "Z790",
      formFactor: "ATX",
      memoryType: "DDR5",
      maxMemory: "192 GB",
      price: "$399",
      rating: 5.0,
      image: "/images/motherboard/z790-rog.jpg"
    }
  ],

  // ---------- Memory ----------
  memory: [
    {
      id: "ram-8-2400",
      type: "memory",
      name: "8GB DDR4 2400",
      brand: "Generic",
      capacityGB: 8,
      speedMHz: 2400,
      memoryType: "DDR4",
      modules: 1,
      price: "$19",
      rating: 4.2,
      image: "/images/memory/8gb-2400.jpg"
    },
    {
      id: "ram-8-2666",
      type: "memory",
      name: "8GB DDR4 2666",
      brand: "Generic",
      capacityGB: 8,
      speedMHz: 2666,
      memoryType: "DDR4",
      modules: 1,
      price: "$22",
      rating: 4.4,
      image: "/images/memory/8gb-2666.jpg"
    },
    {
      id: "ram-8-3200",
      type: "memory",
      name: "Corsair Vengeance 8GB 3200",
      brand: "Corsair",
      capacityGB: 8,
      speedMHz: 3200,
      memoryType: "DDR4",
      modules: 1,
      price: "$29",
      rating: 4.7,
      image: "/images/memory/8gb-3200.jpg"
    },
    {
      id: "ram-16-3200",
      type: "memory",
      name: "Corsair Vengeance 16GB 3200",
      brand: "Corsair",
      capacityGB: 16,
      speedMHz: 3200,
      memoryType: "DDR4",
      modules: 2,
      price: "$49",
      rating: 4.9,
      image: "/images/memory/16gb-3200.jpg"
    },
    {
      id: "ram-16-3600",
      type: "memory",
      name: "G.Skill Ripjaws 16GB 3600",
      brand: "G.Skill",
      capacityGB: 16,
      speedMHz: 3600,
      memoryType: "DDR4",
      modules: 2,
      price: "$69",
      rating: 4.8,
      image: "/images/memory/16gb-3600.jpg"
    },
    {
      id: "ram-32-3200",
      type: "memory",
      name: "32GB DDR4 3200",
      brand: "Corsair",
      capacityGB: 32,
      speedMHz: 3200,
      memoryType: "DDR4",
      modules: 2,
      price: "$99",
      rating: 4.9,
      image: "/images/memory/32gb-3200.jpg"
    },
    {
      id: "ram-32-3600",
      type: "memory",
      name: "32GB DDR4 3600",
      brand: "G.Skill",
      capacityGB: 32,
      speedMHz: 3600,
      memoryType: "DDR4",
      modules: 2,
      price: "$119",
      rating: 4.9,
      image: "/images/memory/32gb-3600.jpg"
    },
    {
      id: "ram-16-ddr5-5600",
      type: "memory",
      name: "16GB DDR5 5600",
      brand: "Kingston",
      capacityGB: 16,
      speedMHz: 5600,
      memoryType: "DDR5",
      modules: 2,
      price: "$89",
      rating: 4.7,
      image: "/images/memory/16gb-ddr5-5600.jpg"
    },
    {
      id: "ram-32-ddr5-6000",
      type: "memory",
      name: "32GB DDR5 6000",
      brand: "Corsair",
      capacityGB: 32,
      speedMHz: 6000,
      memoryType: "DDR5",
      modules: 2,
      price: "$159",
      rating: 4.8,
      image: "/images/memory/32gb-ddr5-6000.jpg"
    },
    {
      id: "ram-64-ddr5-6000",
      type: "memory",
      name: "64GB DDR5 6000",
      brand: "Corsair",
      capacityGB: 64,
      speedMHz: 6000,
      memoryType: "DDR5",
      modules: 2,
      price: "$299",
      rating: 5.0,
      image: "/images/memory/64gb-ddr5-6000.jpg"
    }
  ],

  // ---------- Storage ----------
  storage: [
    {
      id: "st-a400-120",
      type: "storage",
      name: "Kingston A400 120GB",
      brand: "Kingston",
      storageType: "SATA SSD",
      capacity: "120 GB",
      interface: "SATA",
      formFactor: '2.5"',
      price: "$19",
      rating: 4.6,
      image: "/images/storage/a400-120.jpg"
    },
    {
      id: "st-bx500-240",
      type: "storage",
      name: "Crucial BX500 240GB",
      brand: "Crucial",
      storageType: "SATA SSD",
      capacity: "240 GB",
      interface: "SATA",
      formFactor: '2.5"',
      price: "$29",
      rating: 4.8,
      image: "/images/storage/bx500-240.jpg"
    },
    {
      id: "st-ssdplus-240",
      type: "storage",
      name: "SanDisk SSD Plus 240GB",
      brand: "SanDisk",
      storageType: "SATA SSD",
      capacity: "240 GB",
      interface: "SATA",
      formFactor: '2.5"',
      price: "$29",
      rating: 4.6,
      image: "/images/storage/ssdplus-240.jpg"
    },
    {
      id: "st-870evo-1tb",
      type: "storage",
      name: "Samsung 870 EVO 1TB",
      brand: "Samsung",
      storageType: "SATA SSD",
      capacity: "1 TB",
      interface: "SATA",
      formFactor: '2.5"',
      price: "$89",
      rating: 4.9,
      image: "/images/storage/870evo-1tb.jpg"
    },
    {
      id: "st-sn570-500",
      type: "storage",
      name: "WD Blue SN570 500GB",
      brand: "Western Digital",
      storageType: "NVMe",
      capacity: "500 GB",
      interface: "PCIe 3.0",
      formFactor: "M.2",
      price: "$49",
      rating: 4.8,
      image: "/images/storage/sn570-500.jpg"
    },
    {
      id: "st-sn770-1tb",
      type: "storage",
      name: "WD Black SN770 1TB",
      brand: "Western Digital",
      storageType: "NVMe",
      capacity: "1 TB",
      interface: "PCIe 4.0",
      formFactor: "M.2",
      price: "$99",
      rating: 4.9,
      image: "/images/storage/sn770-1tb.jpg"
    },
    {
      id: "st-990pro-1tb",
      type: "storage",
      name: "Samsung 990 Pro 1TB",
      brand: "Samsung",
      storageType: "NVMe",
      capacity: "1 TB",
      interface: "PCIe 4.0",
      formFactor: "M.2",
      price: "$139",
      rating: 5.0,
      image: "/images/storage/990pro-1tb.jpg"
    },
    {
      id: "st-barracuda-500",
      type: "storage",
      name: "Seagate Barracuda 500GB",
      brand: "Seagate",
      storageType: "HDD",
      capacity: "500 GB",
      interface: "SATA",
      formFactor: '3.5"',
      price: "$29",
      rating: 4.2,
      image: "/images/storage/barracuda-500.jpg"
    },
    {
      id: "st-barracuda-1tb",
      type: "storage",
      name: "Seagate Barracuda 1TB",
      brand: "Seagate",
      storageType: "HDD",
      capacity: "1 TB",
      interface: "SATA",
      formFactor: '3.5"',
      price: "$39",
      rating: 4.6,
      image: "/images/storage/barracuda-1tb.jpg"
    },
    {
      id: "st-wdblue-2tb",
      type: "storage",
      name: "WD Blue 2TB",
      brand: "Western Digital",
      storageType: "HDD",
      capacity: "2 TB",
      interface: "SATA",
      formFactor: '3.5"',
      price: "$59",
      rating: 4.7,
      image: "/images/storage/wdblue-2tb.jpg"
    }
  ],

  // ---------- Video Card ----------
  "video-card": [
    {
      id: "gpu-gt-710",
      type: "video-card",
      name: "NVIDIA GT 710",
      brand: "NVIDIA",
      chipset: "GT 710",
      vram: "2 GB",
      length: "150 mm",
      powerConnector: "None",
      recommendedPsu: "300 W",
      tier: "office",
      price: "$49",
      rating: 4.1,
      image: "/images/gpu/gt-710.jpg"
    },
    {
      id: "gpu-gt-1030",
      type: "video-card",
      name: "NVIDIA GT 1030",
      brand: "NVIDIA",
      chipset: "GT 1030",
      vram: "2 GB",
      length: "150 mm",
      powerConnector: "None",
      recommendedPsu: "300 W",
      tier: "budget",
      price: "$79",
      rating: 4.2,
      image: "/images/gpu/gt-1030.jpg"
    },
    {
      id: "gpu-rx-550",
      type: "video-card",
      name: "AMD Radeon RX 550",
      brand: "AMD",
      chipset: "RX 550",
      vram: "4 GB",
      length: "170 mm",
      powerConnector: "None",
      recommendedPsu: "350 W",
      tier: "budget",
      price: "$89",
      rating: 4.3,
      image: "/images/gpu/rx-550.jpg"
    },
    {
      id: "gpu-gtx-1650",
      type: "video-card",
      name: "NVIDIA GTX 1650",
      brand: "NVIDIA",
      chipset: "GTX 1650",
      vram: "4 GB",
      length: "229 mm",
      powerConnector: "6-pin",
      recommendedPsu: "400 W",
      tier: "budget",
      price: "$159",
      rating: 4.6,
      image: "/images/gpu/gtx-1650.jpg"
    },
    {
      id: "gpu-gtx-1660s",
      type: "video-card",
      name: "NVIDIA GTX 1660 Super",
      brand: "NVIDIA",
      chipset: "GTX 1660 Super",
      vram: "6 GB",
      length: "229 mm",
      powerConnector: "8-pin",
      recommendedPsu: "450 W",
      tier: "midrange",
      price: "$199",
      rating: 4.7,
      image: "/images/gpu/gtx-1660s.jpg"
    },
    {
      id: "gpu-rtx-3060",
      type: "video-card",
      name: "NVIDIA RTX 3060",
      brand: "NVIDIA",
      chipset: "RTX 3060",
      vram: "12 GB",
      length: "242 mm",
      powerConnector: "8-pin",
      recommendedPsu: "550 W",
      tier: "midrange",
      price: "$299",
      rating: 4.7,
      image: "/images/gpu/rtx-3060.jpg"
    },
    {
      id: "gpu-rtx-3060ti",
      type: "video-card",
      name: "NVIDIA RTX 3060 Ti",
      brand: "NVIDIA",
      chipset: "RTX 3060 Ti",
      vram: "8 GB",
      length: "242 mm",
      powerConnector: "8-pin",
      recommendedPsu: "600 W",
      tier: "high-end",
      price: "$349",
      rating: 4.8,
      image: "/images/gpu/rtx-3060ti.jpg"
    },
    {
      id: "gpu-rx-6700xt",
      type: "video-card",
      name: "AMD Radeon RX 6700 XT",
      brand: "AMD",
      chipset: "RX 6700 XT",
      vram: "12 GB",
      length: "267 mm",
      powerConnector: "2x 8-pin",
      recommendedPsu: "650 W",
      tier: "high-end",
      price: "$379",
      rating: 4.8,
      image: "/images/gpu/rx-6700xt.jpg"
    },
    {
      id: "gpu-rtx-4070",
      type: "video-card",
      name: "NVIDIA RTX 4070",
      brand: "NVIDIA",
      chipset: "RTX 4070",
      vram: "12 GB",
      length: "244 mm",
      powerConnector: "16-pin",
      recommendedPsu: "650 W",
      tier: "high-end",
      price: "$599",
      rating: 4.9,
      image: "/images/gpu/rtx-4070.jpg"
    },
    {
      id: "gpu-rtx-4090",
      type: "video-card",
      name: "NVIDIA RTX 4090",
      brand: "NVIDIA",
      chipset: "RTX 4090",
      vram: "24 GB",
      length: "304 mm",
      powerConnector: "16-pin",
      recommendedPsu: "850 W",
      tier: "enthusiast",
      price: "$1599",
      rating: 5.0,
      image: "/images/gpu/rtx-4090.jpg"
    }
  ],

  // ---------- Case ----------
  case: [
    {
      id: "case-office-matx",
      type: "case",
      name: "Generic Office mATX Case",
      brand: "Generic",
      formFactor: "mATX",
      gpuMaxLength: "300 mm",
      cpuCoolerMaxHeight: "150 mm",
      psuType: "ATX",
      hasWindow: false,
      tier: "budget",
      price: "$29",
      rating: 3.8,
      image: "/images/case/office-matx.jpg"
    },
    {
      id: "case-versa-h17",
      type: "case",
      name: "Thermaltake Versa H17",
      brand: "Thermaltake",
      formFactor: "mATX",
      gpuMaxLength: "350 mm",
      cpuCoolerMaxHeight: "155 mm",
      psuType: "ATX",
      hasWindow: false,
      tier: "budget",
      price: "$39",
      rating: 4.3,
      image: "/images/case/versa-h17.jpg"
    },
    {
      id: "case-q300l",
      type: "case",
      name: "Cooler Master Q300L",
      brand: "Cooler Master",
      formFactor: "mATX",
      gpuMaxLength: "360 mm",
      cpuCoolerMaxHeight: "159 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "midrange",
      price: "$59",
      rating: 4.6,
      image: "/images/case/q300l.jpg"
    },
    {
      id: "case-phanteks-p300a",
      type: "case",
      name: "Phanteks P300A",
      brand: "Phanteks",
      formFactor: "ATX",
      gpuMaxLength: "355 mm",
      cpuCoolerMaxHeight: "160 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "midrange",
      price: "$69",
      rating: 4.7,
      image: "/images/case/p300a.jpg"
    },
    {
      id: "case-nzxt-h510",
      type: "case",
      name: "NZXT H510",
      brand: "NZXT",
      formFactor: "ATX",
      gpuMaxLength: "381 mm",
      cpuCoolerMaxHeight: "165 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "midrange",
      price: "$79",
      rating: 4.7,
      image: "/images/case/h510.jpg"
    },
    {
      id: "case-corsair-4000d",
      type: "case",
      name: "Corsair 4000D Airflow",
      brand: "Corsair",
      formFactor: "ATX",
      gpuMaxLength: "360 mm",
      cpuCoolerMaxHeight: "170 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "midrange",
      price: "$89",
      rating: 4.8,
      image: "/images/case/4000d.jpg"
    },
    {
      id: "case-fractal-pop-air",
      type: "case",
      name: "Fractal Pop Air",
      brand: "Fractal Design",
      formFactor: "ATX",
      gpuMaxLength: "405 mm",
      cpuCoolerMaxHeight: "170 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "midrange",
      price: "$89",
      rating: 4.8,
      image: "/images/case/pop-air.jpg"
    },
    {
      id: "case-nr200",
      type: "case",
      name: "Cooler Master NR200",
      brand: "Cooler Master",
      formFactor: "Mini-ITX",
      gpuMaxLength: "330 mm",
      cpuCoolerMaxHeight: "155 mm",
      psuType: "SFX",
      hasWindow: false,
      tier: "midrange",
      price: "$89",
      rating: 4.8,
      image: "/images/case/nr200.jpg"
    },
    {
      id: "case-o11-dynamic",
      type: "case",
      name: "Lian Li O11 Dynamic",
      brand: "Lian Li",
      formFactor: "ATX",
      gpuMaxLength: "420 mm",
      cpuCoolerMaxHeight: "155 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "high-end",
      price: "$129",
      rating: 4.9,
      image: "/images/case/o11-dynamic.jpg"
    },
    {
      id: "case-5000d",
      type: "case",
      name: "Corsair 5000D Airflow",
      brand: "Corsair",
      formFactor: "ATX",
      gpuMaxLength: "420 mm",
      cpuCoolerMaxHeight: "170 mm",
      psuType: "ATX",
      hasWindow: true,
      tier: "high-end",
      price: "$149",
      rating: 4.9,
      image: "/images/case/5000d.jpg"
    }
  ],

  // ---------- Power Supply ----------
  "power-supply": [
    {
      id: "psu-evga-400w",
      type: "power-supply",
      name: "EVGA 400W",
      brand: "EVGA",
      wattage: 400,
      efficiency: "80+",
      modular: "No",
      tier: "budget",
      price: "$29",
      rating: 4.1,
      image: "/images/psu/evga-400w.jpg"
    },
    {
      id: "psu-vs450",
      type: "power-supply",
      name: "Corsair VS450",
      brand: "Corsair",
      wattage: 450,
      efficiency: "80+",
      modular: "No",
      tier: "budget",
      price: "$39",
      rating: 4.3,
      image: "/images/psu/vs450.jpg"
    },
    {
      id: "psu-cm-450w",
      type: "power-supply",
      name: "Cooler Master 450W",
      brand: "Cooler Master",
      wattage: 450,
      efficiency: "80+",
      modular: "No",
      tier: "budget",
      price: "$39",
      rating: 4.2,
      image: "/images/psu/cm-450w.jpg"
    },
    {
      id: "psu-s12iii-650",
      type: "power-supply",
      name: "Seasonic S12III 650W",
      brand: "Seasonic",
      wattage: 650,
      efficiency: "80+ Bronze",
      modular: "No",
      tier: "midrange",
      price: "$59",
      rating: 4.6,
      image: "/images/psu/s12iii-650.jpg"
    },
    {
      id: "psu-cx650",
      type: "power-supply",
      name: "Corsair CX650",
      brand: "Corsair",
      wattage: 650,
      efficiency: "80+ Bronze",
      modular: "Semi-modular",
      tier: "midrange",
      price: "$69",
      rating: 4.7,
      image: "/images/psu/cx650.jpg"
    },
    {
      id: "psu-rm750",
      type: "power-supply",
      name: "Corsair RM750",
      brand: "Corsair",
      wattage: 750,
      efficiency: "80+ Gold",
      modular: "Fully modular",
      tier: "high-end",
      price: "$109",
      rating: 4.8,
      image: "/images/psu/rm750.jpg"
    },
    {
      id: "psu-rm850",
      type: "power-supply",
      name: "Corsair RM850",
      brand: "Corsair",
      wattage: 850,
      efficiency: "80+ Gold",
      modular: "Fully modular",
      tier: "high-end",
      price: "$129",
      rating: 4.8,
      image: "/images/psu/rm850.jpg"
    },
    {
      id: "psu-purepower-750",
      type: "power-supply",
      name: "Be Quiet Pure Power 750W",
      brand: "Be Quiet",
      wattage: 750,
      efficiency: "80+ Gold",
      modular: "Semi-modular",
      tier: "high-end",
      price: "$119",
      rating: 4.7,
      image: "/images/psu/purepower-750.jpg"
    },
    {
      id: "psu-thor-1000",
      type: "power-supply",
      name: "ASUS ROG Thor 1000W",
      brand: "ASUS",
      wattage: 1000,
      efficiency: "80+ Platinum",
      modular: "Fully modular",
      tier: "enthusiast",
      price: "$249",
      rating: 4.9,
      image: "/images/psu/thor-1000.jpg"
    },
    {
      id: "psu-msi-a850",
      type: "power-supply",
      name: "MSI MPG A850",
      brand: "MSI",
      wattage: 850,
      efficiency: "80+ Gold",
      modular: "Fully modular",
      tier: "high-end",
      price: "$139",
      rating: 4.7,
      image: "/images/psu/mpg-a850.jpg"
    }
  ],

  // ---------- Operating System ----------
  "operating-system": [
    {
      id: "os-win10-home",
      type: "operating-system",
      name: "Windows 10 Home",
      brand: "Microsoft",
      edition: "Home",
      licenseType: "OEM",
      bit: "64-bit",
      tier: "standard",
      price: "$99",
      rating: 4.5,
      image: "/images/os/win10-home.jpg"
    },
    {
      id: "os-win10-pro",
      type: "operating-system",
      name: "Windows 10 Pro",
      brand: "Microsoft",
      edition: "Pro",
      licenseType: "Retail",
      bit: "64-bit",
      tier: "business",
      price: "$139",
      rating: 4.6,
      image: "/images/os/win10-pro.jpg"
    },
    {
      id: "os-win11-home",
      type: "operating-system",
      name: "Windows 11 Home",
      brand: "Microsoft",
      edition: "Home",
      licenseType: "OEM",
      bit: "64-bit",
      tier: "standard",
      price: "$109",
      rating: 4.3,
      image: "/images/os/win11-home.jpg"
    },
    {
      id: "os-win11-pro",
      type: "operating-system",
      name: "Windows 11 Pro",
      brand: "Microsoft",
      edition: "Pro",
      licenseType: "Retail",
      bit: "64-bit",
      tier: "business",
      price: "$149",
      rating: 4.4,
      image: "/images/os/win11-pro.jpg"
    },
    {
      id: "os-ubuntu",
      type: "operating-system",
      name: "Ubuntu LTS",
      brand: "Canonical",
      edition: "Desktop",
      licenseType: "Free",
      bit: "64-bit",
      tier: "budget",
      price: "$0",
      rating: 4.7,
      image: "/images/os/ubuntu.jpg"
    },
    {
      id: "os-mint",
      type: "operating-system",
      name: "Linux Mint",
      brand: "Linux Mint",
      edition: "Cinnamon",
      licenseType: "Free",
      bit: "64-bit",
      tier: "budget",
      price: "$0",
      rating: 4.6,
      image: "/images/os/mint.jpg"
    },
    {
      id: "os-fedora",
      type: "operating-system",
      name: "Fedora Workstation",
      brand: "Fedora",
      edition: "Workstation",
      licenseType: "Free",
      bit: "64-bit",
      tier: "budget",
      price: "$0",
      rating: 4.5,
      image: "/images/os/fedora.jpg"
    },
    {
      id: "os-popos",
      type: "operating-system",
      name: "Pop!_OS",
      brand: "System76",
      edition: "Desktop",
      licenseType: "Free",
      bit: "64-bit",
      tier: "budget",
      price: "$0",
      rating: 4.6,
      image: "/images/os/popos.jpg"
    },
    {
      id: "os-chrome-flex",
      type: "operating-system",
      name: "ChromeOS Flex",
      brand: "Google",
      edition: "Flex",
      licenseType: "Free",
      bit: "64-bit",
      tier: "budget",
      price: "$0",
      rating: 4.3,
      image: "/images/os/chrome-flex.jpg"
    },
    {
      id: "os-steamos",
      type: "operating-system",
      name: "SteamOS",
      brand: "Valve",
      edition: "Gaming",
      licenseType: "Free",
      bit: "64-bit",
      tier: "gaming",
      price: "$0",
      rating: 4.4,
      image: "/images/os/steamos.jpg"
    }
  ],

  // ---------- Peripherals ----------
  peripherals: [
    {
      id: "periph-b100",
      type: "peripherals",
      name: "Logitech B100 Mouse",
      brand: "Logitech",
      peripheralType: "Mouse",
      connection: "Wired",
      tier: "budget",
      price: "$9",
      rating: 4.5,
      image: "/images/peripherals/b100.jpg"
    },
    {
      id: "periph-mk120",
      type: "peripherals",
      name: "Logitech MK120 Keyboard + Mouse",
      brand: "Logitech",
      peripheralType: "Keyboard + Mouse Combo",
      connection: "Wired",
      tier: "budget",
      price: "$19",
      rating: 4.4,
      image: "/images/peripherals/mk120.jpg"
    },
    {
      id: "periph-office-kb",
      type: "peripherals",
      name: "Generic Office Keyboard",
      brand: "Generic",
      peripheralType: "Keyboard",
      connection: "Wired",
      tier: "budget",
      price: "$12",
      rating: 4.0,
      image: "/images/peripherals/office-kb.jpg"
    },
    {
      id: "periph-g102",
      type: "peripherals",
      name: "Logitech G102 Mouse",
      brand: "Logitech",
      peripheralType: "Mouse",
      connection: "Wired",
      tier: "budget",
      price: "$25",
      rating: 4.7,
      image: "/images/peripherals/g102.jpg"
    },
    {
      id: "periph-g213",
      type: "peripherals",
      name: "Logitech G213 Keyboard",
      brand: "Logitech",
      peripheralType: "Keyboard",
      connection: "Wired",
      tier: "midrange",
      price: "$49",
      rating: 4.6,
      image: "/images/peripherals/g213.jpg"
    },
    {
      id: "periph-k70",
      type: "peripherals",
      name: "Corsair K70 Keyboard",
      brand: "Corsair",
      peripheralType: "Keyboard",
      connection: "Wired",
      tier: "high-end",
      price: "$129",
      rating: 4.8,
      image: "/images/peripherals/k70.jpg"
    },
    {
      id: "periph-cloud2",
      type: "peripherals",
      name: "HyperX Cloud II Headset",
      brand: "HyperX",
      peripheralType: "Headset",
      connection: "Wired",
      tier: "midrange",
      price: "$79",
      rating: 4.8,
      image: "/images/peripherals/cloud2.jpg"
    },
    {
      id: "periph-g733",
      type: "peripherals",
      name: "Logitech G733 Headset",
      brand: "Logitech",
      peripheralType: "Headset",
      connection: "Wireless",
      tier: "high-end",
      price: "$149",
      rating: 4.7,
      image: "/images/peripherals/g733.jpg"
    },
    {
      id: "periph-razer-da",
      type: "peripherals",
      name: "Razer DeathAdder V2",
      brand: "Razer",
      peripheralType: "Mouse",
      connection: "Wired",
      tier: "midrange",
      price: "$49",
      rating: 4.7,
      image: "/images/peripherals/deathadder-v2.jpg"
    },
    {
      id: "periph-razer-huntsman",
      type: "peripherals",
      name: "Razer Huntsman Keyboard",
      brand: "Razer",
      peripheralType: "Keyboard",
      connection: "Wired",
      tier: "high-end",
      price: "$149",
      rating: 4.6,
      image: "/images/peripherals/huntsman.jpg"
    }
  ],

  // ---------- Expansion Cards ----------
  "expansion-card": [
    {
      id: "exp-wifi-n",
      type: "expansion-card",
      name: "Basic PCIe WiFi N Card",
      brand: "Generic",
      interface: "PCIe x1",
      function: "WiFi",
      tier: "budget",
      price: "$15",
      rating: 4.1,
      image: "/images/expansion/wifi-n.jpg"
    },
    {
      id: "exp-wifi-ac",
      type: "expansion-card",
      name: "PCIe WiFi AC1200 Card",
      brand: "Generic",
      interface: "PCIe x1",
      function: "WiFi",
      tier: "budget",
      price: "$25",
      rating: 4.3,
      image: "/images/expansion/wifi-ac.jpg"
    },
    {
      id: "exp-wifi6",
      type: "expansion-card",
      name: "TP-Link WiFi 6 PCIe Card",
      brand: "TP-Link",
      interface: "PCIe x1",
      function: "WiFi",
      tier: "midrange",
      price: "$39",
      rating: 4.5,
      image: "/images/expansion/wifi6.jpg"
    },
    {
      id: "exp-usb3",
      type: "expansion-card",
      name: "PCIe USB 3.0 Expansion",
      brand: "Generic",
      interface: "PCIe x1",
      function: "USB 3.0 ports",
      tier: "budget",
      price: "$19",
      rating: 4.2,
      image: "/images/expansion/usb3.jpg"
    },
    {
      id: "exp-usbc",
      type: "expansion-card",
      name: "PCIe USB-C Expansion",
      brand: "Generic",
      interface: "PCIe x1",
      function: "USB-C ports",
      tier: "midrange",
      price: "$29",
      rating: 4.3,
      image: "/images/expansion/usbc.jpg"
    },
    {
      id: "exp-sound-basic",
      type: "expansion-card",
      name: "Basic PCIe Sound Card",
      brand: "Generic",
      interface: "PCIe x1",
      function: "Sound",
      tier: "budget",
      price: "$25",
      rating: 4.0,
      image: "/images/expansion/sound-basic.jpg"
    },
    {
      id: "exp-sound-sb",
      type: "expansion-card",
      name: "Sound Blaster Sound Card",
      brand: "Creative",
      interface: "PCIe x1",
      function: "Sound",
      tier: "midrange",
      price: "$49",
      rating: 4.4,
      image: "/images/expansion/sound-blaster.jpg"
    },
    {
      id: "exp-capture-budget",
      type: "expansion-card",
      name: "Budget Capture Card PCIe",
      brand: "Generic",
      interface: "PCIe x1",
      function: "Capture",
      tier: "budget",
      price: "$39",
      rating: 4.0,
      image: "/images/expansion/capture-budget.jpg"
    },
    {
      id: "exp-capture-elgato",
      type: "expansion-card",
      name: "Elgato HD60 Pro",
      brand: "Elgato",
      interface: "PCIe x1",
      function: "Capture",
      tier: "high-end",
      price: "$169",
      rating: 4.7,
      image: "/images/expansion/elgato-hd60.jpg"
    },
    {
      id: "exp-2.5g-lan",
      type: "expansion-card",
      name: "2.5G Ethernet PCIe Card",
      brand: "Generic",
      interface: "PCIe x1",
      function: "Ethernet",
      tier: "midrange",
      price: "$39",
      rating: 4.3,
      image: "/images/expansion/2.5g-lan.jpg"
    }
  ],

  // ---------- Accessories / Other ----------
  accessories: [
    {
      id: "acc-rgb-fan-pack",
      type: "accessories",
      name: "RGB Fan Pack (3x 120mm)",
      brand: "Generic",
      accessoryType: "Cooling / RGB",
      tier: "budget",
      price: "$29",
      rating: 4.3,
      image: "/images/accessories/rgb-fan-pack.jpg"
    },
    {
      id: "acc-single-fan",
      type: "accessories",
      name: "120mm Case Fan",
      brand: "Generic",
      accessoryType: "Cooling",
      tier: "budget",
      price: "$9",
      rating: 4.2,
      image: "/images/accessories/single-fan.jpg"
    },
    {
      id: "acc-thermal-paste",
      type: "accessories",
      name: "Thermal Paste Tube",
      brand: "Generic",
      accessoryType: "Thermal",
      tier: "budget",
      price: "$5",
      rating: 4.6,
      image: "/images/accessories/thermal-paste.jpg"
    },
    {
      id: "acc-rgb-strip",
      type: "accessories",
      name: "RGB LED Strip Kit",
      brand: "Generic",
      accessoryType: "RGB lighting",
      tier: "budget",
      price: "$15",
      rating: 4.2,
      image: "/images/accessories/rgb-strip.jpg"
    },
    {
      id: "acc-cable-ties",
      type: "accessories",
      name: "Cable Tie Pack",
      brand: "Generic",
      accessoryType: "Cable management",
      tier: "budget",
      price: "$4",
      rating: 4.5,
      image: "/images/accessories/cable-ties.jpg"
    },
    {
      id: "acc-dust-filters",
      type: "accessories",
      name: "Magnetic Dust Filter Kit",
      brand: "Generic",
      accessoryType: "Dust filter",
      tier: "budget",
      price: "$12",
      rating: 4.4,
      image: "/images/accessories/dust-filters.jpg"
    },
    {
      id: "acc-ssd-bracket",
      type: "accessories",
      name: "2.5\" SSD Mounting Bracket",
      brand: "Generic",
      accessoryType: "Mounting",
      tier: "budget",
      price: "$8",
      rating: 4.3,
      image: "/images/accessories/ssd-bracket.jpg"
    },
    {
      id: "acc-pcie-riser",
      type: "accessories",
      name: "PCIe Riser Cable",
      brand: "Generic",
      accessoryType: "Riser",
      tier: "midrange",
      price: "$29",
      rating: 4.1,
      image: "/images/accessories/pcie-riser.jpg"
    },
    {
      id: "acc-vertical-gpu-mount",
      type: "accessories",
      name: "Vertical GPU Mount",
      brand: "Generic",
      accessoryType: "Mounting",
      tier: "midrange",
      price: "$39",
      rating: 4.2,
      image: "/images/accessories/vertical-gpu-mount.jpg"
    },
    {
      id: "acc-fan-hub",
      type: "accessories",
      name: "Fan Hub Controller",
      brand: "Generic",
      accessoryType: "Fan controller",
      tier: "midrange",
      price: "$25",
      rating: 4.4,
      image: "/images/accessories/fan-hub.jpg"
    }
  ]
};

export default mockParts;
